export const AutofillSuggestions = [
  'apple',
  'apples',
  'orange',
  'pear',
  'oranges',
  'pears',
  'honeycrisp apple',
  'raspberry',
  'raspberries',
  'blueberry',
  'blueberries',
  'strawberry',
  'strawberries',
  'banana',
  'bananas',
  'melon',
  'melons',
  'watermelon',
  'watermelons',
  'honeydew',
  'honeydews',
  'cantaloupe',
  'cantaloupes'];